app = "ai-automation-server"
primary_region = "sjc"

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[env]
  NODE_ENV = "production"

[[services]]
  protocol = "tcp"
  internal_port = 3003
  processes = ["app"]

  [[services.ports]]
    port = "80"
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = "443"
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "1s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
