services:
  - type: web
    name: ai-automation-server
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install && npx playwright install chromium --with-deps || echo "Browser install failed, will try at runtime"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
