services:
  - type: web
    name: ai-automation-server
    env: node
    region: oregon
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false # Let the platform set the port
    healthCheckPath: /health
